### ISSUE TITLE
Modulo parse error

### ISSUE THREAD

**Issue by DanPurdy** [DanPurdy/gonzales-pe#7]
The following is throwing a parse error due to the modulo operator being present.

``` scss
@for $i from 1 through length($listColors) {
    #{$i*(100/length($listColors))}% {
      fill: nth($listColors, $i);
    }
  }
```

When placed in the following context the whole of the above block is throwing a parse error even if the modulo operator is removed.

``` scss
@keyframes pweek {
  0% {
    fill: $firstColor;
  }
  @for $i from 1 through length($listColors) {
    #{$i*(100/length($listColors))}% {
      fill: nth($listColors, $i);
    }
  }
}
```
